// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "xsd-top-albums.hxx"

namespace LastFM
{
  // topalbums
  // 

  const topalbums::album_sequence& topalbums::
  album () const
  {
    return this->album_;
  }

  topalbums::album_sequence& topalbums::
  album ()
  {
    return this->album_;
  }

  void topalbums::
  album (const album_sequence& album)
  {
    this->album_ = album;
  }

  const topalbums::artist_optional& topalbums::
  artist () const
  {
    return this->artist_;
  }

  topalbums::artist_optional& topalbums::
  artist ()
  {
    return this->artist_;
  }

  void topalbums::
  artist (const artist_type& artist)
  {
    this->artist_.set (artist);
  }

  void topalbums::
  artist (const artist_optional& artist)
  {
    this->artist_ = artist;
  }

  void topalbums::
  artist (::std::auto_ptr< artist_type > artist)
  {
    this->artist_.set (artist);
  }


  // album
  // 

  const album::name_type& album::
  name () const
  {
    return this->name_.get ();
  }

  album::name_type& album::
  name ()
  {
    return this->name_.get ();
  }

  void album::
  name (const name_type& name)
  {
    this->name_.set (name);
  }

  void album::
  name (::std::auto_ptr< name_type > name)
  {
    this->name_.set (name);
  }

  const album::mbid_type& album::
  mbid () const
  {
    return this->mbid_.get ();
  }

  album::mbid_type& album::
  mbid ()
  {
    return this->mbid_.get ();
  }

  void album::
  mbid (const mbid_type& mbid)
  {
    this->mbid_.set (mbid);
  }

  void album::
  mbid (::std::auto_ptr< mbid_type > mbid)
  {
    this->mbid_.set (mbid);
  }

  const album::reach_type& album::
  reach () const
  {
    return this->reach_.get ();
  }

  album::reach_type& album::
  reach ()
  {
    return this->reach_.get ();
  }

  void album::
  reach (const reach_type& reach)
  {
    this->reach_.set (reach);
  }

  const album::url_type& album::
  url () const
  {
    return this->url_.get ();
  }

  album::url_type& album::
  url ()
  {
    return this->url_.get ();
  }

  void album::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void album::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }

  const album::image_type& album::
  image () const
  {
    return this->image_.get ();
  }

  album::image_type& album::
  image ()
  {
    return this->image_.get ();
  }

  void album::
  image (const image_type& image)
  {
    this->image_.set (image);
  }

  void album::
  image (::std::auto_ptr< image_type > image)
  {
    this->image_.set (image);
  }


  // image
  // 

  const image::large_type& image::
  large () const
  {
    return this->large_.get ();
  }

  image::large_type& image::
  large ()
  {
    return this->large_.get ();
  }

  void image::
  large (const large_type& large)
  {
    this->large_.set (large);
  }

  void image::
  large (::std::auto_ptr< large_type > large)
  {
    this->large_.set (large);
  }

  const image::medium_type& image::
  medium () const
  {
    return this->medium_.get ();
  }

  image::medium_type& image::
  medium ()
  {
    return this->medium_.get ();
  }

  void image::
  medium (const medium_type& medium)
  {
    this->medium_.set (medium);
  }

  void image::
  medium (::std::auto_ptr< medium_type > medium)
  {
    this->medium_.set (medium);
  }

  const image::small_type& image::
  small () const
  {
    return this->small_.get ();
  }

  image::small_type& image::
  small ()
  {
    return this->small_.get ();
  }

  void image::
  small (const small_type& small)
  {
    this->small_.set (small);
  }

  void image::
  small (::std::auto_ptr< small_type > small)
  {
    this->small_.set (small);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace LastFM
{
  // topalbums
  //

  topalbums::
  topalbums ()
  : ::xml_schema::type (),
    album_ (::xml_schema::flags (), this),
    artist_ (::xml_schema::flags (), this)
  {
  }

  topalbums::
  topalbums (const topalbums& x,
             ::xml_schema::flags f,
             ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    album_ (x.album_, f, this),
    artist_ (x.artist_, f, this)
  {
  }

  topalbums::
  topalbums (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    album_ (f, this),
    artist_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void topalbums::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // album
      //
      if (n.name () == "album" )
      {
        ::std::auto_ptr< album_type > r (
          album_traits::create (i, f, this));

        this->album ().push_back (r);
        continue;
      }

      break;
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "artist" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        this->artist (r);
        continue;
      }
    }
  }

  topalbums* topalbums::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new topalbums (*this, f, c);
  }

  // album
  //

  album::
  album (const name_type& name,
         const mbid_type& mbid,
         const reach_type& reach,
         const url_type& url,
         const image_type& image)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    mbid_ (mbid, ::xml_schema::flags (), this),
    reach_ (reach, ::xml_schema::flags (), this),
    url_ (url, ::xml_schema::flags (), this),
    image_ (image, ::xml_schema::flags (), this)
  {
  }

  album::
  album (const album& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    mbid_ (x.mbid_, f, this),
    reach_ (x.reach_, f, this),
    url_ (x.url_, f, this),
    image_ (x.image_, f, this)
  {
  }

  album::
  album (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    mbid_ (f, this),
    reach_ (f, this),
    url_ (f, this),
    image_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void album::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" )
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // mbid
      //
      if (n.name () == "mbid" )
      {
        ::std::auto_ptr< mbid_type > r (
          mbid_traits::create (i, f, this));

        if (!mbid_.present ())
        {
          this->mbid (r);
          continue;
        }
      }

      // reach
      //
      if (n.name () == "reach" )
      {
        if (!reach_.present ())
        {
          this->reach (reach_traits::create (i, f, this));
          continue;
        }
      }

      // url
      //
      if (n.name () == "url" )
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      // image
      //
      if (n.name () == "image" )
      {
        ::std::auto_ptr< image_type > r (
          image_traits::create (i, f, this));

        if (!image_.present ())
        {
          this->image (r);
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "LastFM");
    }

    if (!mbid_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mbid",
        "LastFM");
    }

    if (!reach_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "reach",
        "LastFM");
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "LastFM");
    }

    if (!image_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "image",
        "LastFM");
    }
  }

  album* album::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new album (*this, f, c);
  }

  // image
  //

  image::
  image (const large_type& large,
         const medium_type& medium,
         const small_type& small)
  : ::xml_schema::type (),
    large_ (large, ::xml_schema::flags (), this),
    medium_ (medium, ::xml_schema::flags (), this),
    small_ (small, ::xml_schema::flags (), this)
  {
  }

  image::
  image (const image& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    large_ (x.large_, f, this),
    medium_ (x.medium_, f, this),
    small_ (x.small_, f, this)
  {
  }

  image::
  image (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    large_ (f, this),
    medium_ (f, this),
    small_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void image::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // large
      //
      if (n.name () == "large" )
      {
        ::std::auto_ptr< large_type > r (
          large_traits::create (i, f, this));

        if (!large_.present ())
        {
          this->large (r);
          continue;
        }
      }

      // medium
      //
      if (n.name () == "medium" )
      {
        ::std::auto_ptr< medium_type > r (
          medium_traits::create (i, f, this));

        if (!medium_.present ())
        {
          this->medium (r);
          continue;
        }
      }

      // small
      //
      if (n.name () == "small" )
      {
        ::std::auto_ptr< small_type > r (
          small_traits::create (i, f, this));

        if (!small_.present ())
        {
          this->small (r);
          continue;
        }
      }

      break;
    }

    if (!large_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "large",
        "LastFM");
    }

    if (!medium_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "medium",
        "LastFM");
    }

    if (!small_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "small",
        "LastFM");
    }
  }

  image* image::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new image (*this, f, c);
  }
}

#include <istream>
#include <xercesc/framework/Wrapper4InputSource.hpp>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace LastFM
{
  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::std::string& u,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::std::string& u,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::std::string& u,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::std::istream& is,
              const ::std::string& sid,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::topalbums_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::xercesc::DOMInputSource& i,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::xercesc::DOMInputSource& i,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::xercesc::DOMInputSource& i,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::topalbums > r (
      ::LastFM::topalbums_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (const ::xercesc::DOMDocument& d,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::LastFM::topalbums > r (
        ::LastFM::topalbums_ (
          c.get (), f | ::xml_schema::flags::own_dom, p));

      c.release ();
      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "topalbums" &&
        n.namespace_ () == "LastFM")
    {
      ::std::auto_ptr< ::LastFM::topalbums > r (
        ::xsd::cxx::tree::traits< ::LastFM::topalbums, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "topalbums",
      "LastFM");
  }

  ::std::auto_ptr< ::LastFM::topalbums >
  topalbums_ (::xercesc::DOMDocument* d,
              ::xml_schema::flags f,
              const ::xml_schema::properties&)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    const ::xercesc::DOMElement& e (
      c.get ()
      ? *c->getDocumentElement ()
      : *d->getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "topalbums" &&
        n.namespace_ () == "LastFM")
    {
      ::std::auto_ptr< ::LastFM::topalbums > r (
        ::xsd::cxx::tree::traits< ::LastFM::topalbums, char >::create (
          e, f, 0));
      c.release ();
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "topalbums",
      "LastFM");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

