// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "xsd-fans.hxx"

namespace LastFM
{
  // similarartists
  // 

  const similarartists::user_sequence& similarartists::
  user () const
  {
    return this->user_;
  }

  similarartists::user_sequence& similarartists::
  user ()
  {
    return this->user_;
  }

  void similarartists::
  user (const user_sequence& user)
  {
    this->user_ = user;
  }

  const similarartists::artist_optional& similarartists::
  artist () const
  {
    return this->artist_;
  }

  similarartists::artist_optional& similarartists::
  artist ()
  {
    return this->artist_;
  }

  void similarartists::
  artist (const artist_type& artist)
  {
    this->artist_.set (artist);
  }

  void similarartists::
  artist (const artist_optional& artist)
  {
    this->artist_ = artist;
  }

  void similarartists::
  artist (::std::auto_ptr< artist_type > artist)
  {
    this->artist_.set (artist);
  }


  // user
  // 

  const user::url_type& user::
  url () const
  {
    return this->url_.get ();
  }

  user::url_type& user::
  url ()
  {
    return this->url_.get ();
  }

  void user::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void user::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }

  const user::image_type& user::
  image () const
  {
    return this->image_.get ();
  }

  user::image_type& user::
  image ()
  {
    return this->image_.get ();
  }

  void user::
  image (const image_type& image)
  {
    this->image_.set (image);
  }

  void user::
  image (::std::auto_ptr< image_type > image)
  {
    this->image_.set (image);
  }

  const user::weight_type& user::
  weight () const
  {
    return this->weight_.get ();
  }

  user::weight_type& user::
  weight ()
  {
    return this->weight_.get ();
  }

  void user::
  weight (const weight_type& weight)
  {
    this->weight_.set (weight);
  }

  const user::username_optional& user::
  username () const
  {
    return this->username_;
  }

  user::username_optional& user::
  username ()
  {
    return this->username_;
  }

  void user::
  username (const username_type& username)
  {
    this->username_.set (username);
  }

  void user::
  username (const username_optional& username)
  {
    this->username_ = username;
  }

  void user::
  username (::std::auto_ptr< username_type > username)
  {
    this->username_.set (username);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace LastFM
{
  // similarartists
  //

  similarartists::
  similarartists ()
  : ::xml_schema::type (),
    user_ (::xml_schema::flags (), this),
    artist_ (::xml_schema::flags (), this)
  {
  }

  similarartists::
  similarartists (const similarartists& x,
                  ::xml_schema::flags f,
                  ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    user_ (x.user_, f, this),
    artist_ (x.artist_, f, this)
  {
  }

  similarartists::
  similarartists (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    user_ (f, this),
    artist_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void similarartists::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // user
      //
      if (n.name () == "user" && n.namespace_ () == "LastFM")
      {
        ::std::auto_ptr< user_type > r (
          user_traits::create (i, f, this));

        this->user ().push_back (r);
        continue;
      }

      break;
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "artist" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        this->artist (r);
        continue;
      }
    }
  }

  similarartists* similarartists::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new similarartists (*this, f, c);
  }

  // user
  //

  user::
  user (const url_type& url,
        const image_type& image,
        const weight_type& weight)
  : ::xml_schema::type (),
    url_ (url, ::xml_schema::flags (), this),
    image_ (image, ::xml_schema::flags (), this),
    weight_ (weight, ::xml_schema::flags (), this),
    username_ (::xml_schema::flags (), this)
  {
  }

  user::
  user (const user& x,
        ::xml_schema::flags f,
        ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    url_ (x.url_, f, this),
    image_ (x.image_, f, this),
    weight_ (x.weight_, f, this),
    username_ (x.username_, f, this)
  {
  }

  user::
  user (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    url_ (f, this),
    image_ (f, this),
    weight_ (f, this),
    username_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void user::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "LastFM")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      // image
      //
      if (n.name () == "image" && n.namespace_ () == "LastFM")
      {
        ::std::auto_ptr< image_type > r (
          image_traits::create (i, f, this));

        if (!image_.present ())
        {
          this->image (r);
          continue;
        }
      }

      // weight
      //
      if (n.name () == "weight" && n.namespace_ () == "LastFM")
      {
        if (!weight_.present ())
        {
          this->weight (weight_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "LastFM");
    }

    if (!image_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "image",
        "LastFM");
    }

    if (!weight_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "weight",
        "LastFM");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "username" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< username_type > r (
          username_traits::create (i, f, this));

        this->username (r);
        continue;
      }
    }
  }

  user* user::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new user (*this, f, c);
  }
}

#include <istream>
#include <xercesc/framework/Wrapper4InputSource.hpp>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace LastFM
{
  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::std::string& u,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::std::string& u,
                   ::xml_schema::error_handler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::std::string& u,
                   ::xercesc::DOMErrorHandler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   ::xml_schema::error_handler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   ::xercesc::DOMErrorHandler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   const ::std::string& sid,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   const ::std::string& sid,
                   ::xml_schema::error_handler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::std::istream& is,
                   const ::std::string& sid,
                   ::xercesc::DOMErrorHandler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFM::similarartists_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::xercesc::DOMInputSource& i,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::xercesc::DOMInputSource& i,
                   ::xml_schema::error_handler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::xercesc::DOMInputSource& i,
                   ::xercesc::DOMErrorHandler& h,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFM::similarartists > r (
      ::LastFM::similarartists_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (const ::xercesc::DOMDocument& d,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::LastFM::similarartists > r (
        ::LastFM::similarartists_ (
          c.get (), f | ::xml_schema::flags::own_dom, p));

      c.release ();
      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "similarartists" &&
        n.namespace_ () == "LastFM")
    {
      ::std::auto_ptr< ::LastFM::similarartists > r (
        ::xsd::cxx::tree::traits< ::LastFM::similarartists, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "similarartists",
      "LastFM");
  }

  ::std::auto_ptr< ::LastFM::similarartists >
  similarartists_ (::xercesc::DOMDocument* d,
                   ::xml_schema::flags f,
                   const ::xml_schema::properties&)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    const ::xercesc::DOMElement& e (
      c.get ()
      ? *c->getDocumentElement ()
      : *d->getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "similarartists" &&
        n.namespace_ () == "LastFM")
    {
      ::std::auto_ptr< ::LastFM::similarartists > r (
        ::xsd::cxx::tree::traits< ::LastFM::similarartists, char >::create (
          e, f, 0));
      c.release ();
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "similarartists",
      "LastFM");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

