
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__mpx_mlibman_dbus_proxy_hh__PROXY_MARSHAL_H
#define __dbusxx__mpx_mlibman_dbus_proxy_hh__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace info {
namespace backtrace {
namespace Youki {

class MLibMan_proxy
 : public ::DBus::InterfaceProxy
{
public:

    MLibMan_proxy()
    : ::DBus::InterfaceProxy("info.backtrace.Youki.MLibMan")
    {
        connect_signal(MLibMan_proxy, ScanStart, _ScanStart_stub);
        connect_signal(MLibMan_proxy, ScanEnd, _ScanEnd_stub);
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void ShowWindow()
    {
        ::DBus::CallMessage call;
        call.member("ShowWindow");
        ::DBus::Message ret = invoke_method(call);
    }

    void Exit()
    {
        ::DBus::CallMessage call;
        call.member("Exit");
        ::DBus::Message ret = invoke_method(call);
    }


public:

    /* signal handlers for this interface
     */
    virtual void ScanStart() = 0;
    virtual void ScanEnd() = 0;

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
    void _ScanStart_stub(const ::DBus::SignalMessage &sig)
    {
        ScanStart();
    }
    void _ScanEnd_stub(const ::DBus::SignalMessage &sig)
    {
        ScanEnd();
    }
};

} } } 
#endif//__dbusxx__mpx_mlibman_dbus_proxy_hh__PROXY_MARSHAL_H
