FIND_PATH(XERCESC_INCLUDE_DIR xercesc
  HINTS $ENV{XERCESCDIR}
)
 
FIND_LIBRARY(XERCESC_LIBRARY xerces-c
  HINTS $ENV{XERCESDIR}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(XercesC DEFAULT_MSG XERCESC_LIBRARY XERCESC_INCLUDE_DIR)
