FIND_PATH(SIDPLAY_INCLUDE_DIR sidplay
  HINTS $ENV{SIDPLAYDIR}
)
 
FIND_LIBRARY(SIDPLAY_LIBRARY sidplay
  HINTS $ENV{SIDPLAYDIR}
)

SET(SIDPLAY_FOUND "NO")
IF(SIDPLAY_LIBRARY AND SIDPLAY_INCLUDE_DIR)
  SET(SIDPLAY_FOUND "YES")
ENDIF(SIDPLAY_LIBRARY AND SIDPLAY_INCLUDE_DIR)
