PKG_CHECK_MODULES(CDIO libcdio_cdda>=0.70)

FIND_PATH(CDDA_INCLUDE_DIR cdda/cdda_interface.h
  HINTS $ENV{CDDADIR}
)

FIND_LIBRARY(CDDA_LIBRARY
  cdda_interface
  HINTS $ENV{CDDADIR}
)

SET(CDDA_FOUND "NO")
IF(CDDA_INCLUDE_DIR AND CDDA_LIBRARY)
  SET(CDDA_FOUND "YES")
ENDIF(CDDA_INCLUDE_DIR AND CDDA_LIBRARY)
