FIND_PATH(SIDPLAY_INCLUDE_DIR
  NAMES sidplay
  HINTS $ENV{SIDPLAYDIR}
  PATH_SUFFIXES include
  PATHS /usr/local /usr /opt/local opt
)
 
FIND_LIBRARY(SIDPLAY_LIBRARY
  NAMES sidplay
  HINTS $ENV{SIDPLAYDIR}
  PATH_SUFFIXES lib64 lib
  PATHS /usr/local /usr /opt/local opt
)

SET(SIDPLAY_FOUND "NO")
IF(SIDPLAY_LIBRARY AND SIDPLAY_INCLUDE_DIR)
  SET(SIDPLAY_FOUND "YES")
ENDIF(SIDPLAY_LIBRARY AND SIDPLAY_INCLUDE_DIR)
