FIND_PATH(CDPARANOIA_INCLUDE_DIR cdda/cdda_interface.h
  HINTS $ENV{CDPARANOIA_PREFIX}
)

FIND_LIBRARY(CDPARANOIA_LIBRARY
  cdda_interface
  HINTS $ENV{CDPARANOIA_PREFIX}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CDPARANOIA
  DEFAULT_MSG
  CDPARANOIA_INCLUDE_DIR
  CDPARANOIA_LIBRARY
)
