#PKG_CHECK_MODULES(SM sm)

IF(NOT SM_FOUND)
  FIND_PATH(SM_INCLUDE_DIR SM
    HINTS $ENV{SMDIR}
  )

  FIND_LIBRARY(SM_LIBRARY SM
    HINTS $ENV{SMDIR}
  )

  FIND_LIBRARY(ICE_LIBRARY ICE
    HINTS $ENV{SMDIR}
  )

  IF(SM_INCLUDE_DIR AND SM_LIBRARY AND ICE_LIBRARY)
    SET(SM_FOUND "YES")
    SET(SM_LIBRARIES ${SM_LIBRARY} ${ICE_LIBRARY})
  ENDIF(SM_INCLUDE_DIR AND SM_LIBRARY AND ICE_LIBRARY)

ENDIF(NOT SM_FOUND)
