FIND_PATH(SIDPLAY_INCLUDE_DIR sidplay
  HINTS $ENV{SIDPLAY_PREFIX}
)
 
FIND_LIBRARY(SIDPLAY_LIBRARY sidplay
  HINTS $ENV{SIDPLAY_PREFIX}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SIDPLAY SIDPLAY_LIBRARY SIDPLAY_INCLUDE_DIR)
