FIND_PATH(XERCESC_INCLUDE_DIR
  NAMES xercesc
  HINTS $ENV{XERCESCDIR}
)
 
FIND_LIBRARY(XERCESC_LIBRARY xerces-c
  HINTS $ENV{XERCESDIR}
)

SET(XERCESC_FOUND "NO")
IF(XERCESC_LIBRARY AND XERCESC_INCLUDE_DIR)
  SET(XERCESC_FOUND "YES")
ENDIF(XERCESC_LIBRARY AND XERCESC_INCLUDE_DIR)
