#pkg_check_modules (SM sm)

IF(NOT SM_FOUND)
  FIND_PATH(SM_INCLUDE_DIR
    NAMES SM
    HINTS $ENV{SMDIR}
    PATHS /usr/local /usr /opt/local /opt
    PATH_SUFFIXES include/X11 include X11R6/include
  )

  FIND_LIBRARY(SM_LIBRARY
    NAMES SM
    HINTS $ENV{SMDIR}
    PATHS /usr/local/X11R6 /usr/X11R6 /opt/local/X11R6 /opt/X11R6
    PATH_SUFFIXES lib64 lib
  )

  FIND_LIBRARY(ICE_LIBRARY
    NAMES ICE
    HINTS $ENV{SMDIR}
    PATHS /usr/local/X11R6 /usr/X11R6 /opt/local/X11R6 /opt/X11R6
    PATH_SUFFIXES lib64 lib
  )

  IF(SM_INCLUDE_DIR AND SM_LIBRARY AND ICE_LIBRARY)
    SET(SM_FOUND "YES")
    SET(SM_LIBRARIES ${SM_LIBRARY} ${ICE_LIBRARY})
  ENDIF(SM_INCLUDE_DIR AND SM_LIBRARY AND ICE_LIBRARY)

ENDIF(NOT SM_FOUND)
