MESSAGE(STATUS "checking for C++ TR1 extensions")

TRY_RUN(TR1_TEST_EXITCODE TR1_TEST_COMPILED
  ${CMAKE_BINARY_DIR}
  ${PROJECT_SOURCE_DIR}/cmake/tr1-test.cpp
)

IF(TR1_TEST_EXITCODE EQUAL 0)
  MESSAGE(STATUS "  C++ TR1 extensions found")
  SET(TR1_FOUND "YES")
ELSE(TR1_TEST_EXITCODE EQUAL 0)
  MESSAGE(STATUS "  C++ TR1 extensions not found")
  SET(TR1_FOUND "NO")
ENDIF(TR1_TEST_EXITCODE EQUAL 0)
